/** Catálogo editorial local: ids estables, independiente de los ejercicios guardados por el usuario. */
import { type Musculo } from './musculos'
export { MUSCULOS, type Musculo } from './musculos'
export const EQUIPAMIENTO = {
  corporal: 'Peso corporal', mancuernas: 'Mancuernas', barra: 'Barra', maquina: 'Máquina', polea: 'Polea',
  smith: 'Smith / Multipower', kettlebell: 'Kettlebell', bandas: 'Bandas', trx: 'TRX', otros: 'Otros',
} as const
export type Equipo = keyof typeof EQUIPAMIENTO
export interface CatalogExercise {
  id: string
  name: string
  primaryMuscles: Musculo[]
  secondaryMuscles: Musculo[]
  equipment: Equipo[]
  aliases?: string[]
  /** Agrupación de búsqueda, separada de la participación anatómica. */
  filterGroups?: Musculo[]
}

/** Los ids son editoriales, no se recalculan al cambiar una etiqueta. Banco es auxiliar, no equipo principal. */
function grupo(primary: Musculo, rows: string[]): CatalogExercise[] {
  return rows.map(row => {
    const [id, name, equipment, secondary = '', aliases = ''] = row.split('|')
    return { id: `appfit:${id}`, name, primaryMuscles: [primary], secondaryMuscles: secondary ? secondary.split(',') as Musculo[] : [], equipment: equipment.split(',') as Equipo[], aliases: aliases ? aliases.split(',') : [] }
  })
}

/** Cuerpo completo agrupa la búsqueda; el mapa necesita músculos concretos, no pintar todo por defecto. */
const PARTICIPACION_COMPLETA: Record<string, Pick<CatalogExercise, 'primaryMuscles' | 'secondaryMuscles'>> = {
  'appfit:peso-muerto': { primaryMuscles: ['gluteos', 'isquiotibiales'], secondaryMuscles: ['espalda', 'antebrazo', 'cuadriceps', 'core'] },
  'appfit:peso-muerto-sumo': { primaryMuscles: ['gluteos', 'cuadriceps'], secondaryMuscles: ['aductores', 'isquiotibiales', 'espalda', 'antebrazo', 'core'] },
  'appfit:swing-kettlebell': { primaryMuscles: ['gluteos', 'isquiotibiales'], secondaryMuscles: ['core', 'espalda', 'hombros'] },
  'appfit:thruster': { primaryMuscles: ['cuadriceps', 'hombros'], secondaryMuscles: ['gluteos', 'core', 'triceps'] },
  'appfit:burpee': { primaryMuscles: ['pecho', 'cuadriceps'], secondaryMuscles: ['triceps', 'hombros', 'gluteos', 'core'] },
  'appfit:farmer-walk': { primaryMuscles: ['antebrazo'], secondaryMuscles: ['hombros', 'espalda', 'core'] },
  'appfit:cargada-barra': { primaryMuscles: ['cuadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiales', 'espalda', 'hombros', 'antebrazo', 'core'] },
  'appfit:peso-muerto-trap-bar': { primaryMuscles: ['cuadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiales', 'espalda', 'antebrazo', 'core'] },
  'appfit:empuje-trineo': { primaryMuscles: ['cuadriceps', 'gluteos'], secondaryMuscles: ['gemelos', 'isquiotibiales', 'hombros', 'triceps', 'core'] },
  'appfit:turkish-get-up': { primaryMuscles: ['core', 'hombros'], secondaryMuscles: ['cuadriceps', 'gluteos', 'triceps'] },
}

export const CATALOGO_EJERCICIOS: CatalogExercise[] = [
  ...grupo('pecho', [
    'press-banca|Press banca|barra|triceps,hombros|bench press',
    'press-inclinado-barra|Press inclinado con barra|barra|triceps,hombros',
    'press-declinado-barra|Press declinado con barra|barra|triceps,hombros',
    'press-mancuernas|Press con mancuernas|mancuernas|triceps,hombros',
    'press-inclinado-mancuernas|Press inclinado con mancuernas|mancuernas|triceps,hombros',
    'aperturas-mancuernas|Aperturas con mancuernas|mancuernas|hombros',
    'pullover-mancuerna|Pullover con mancuerna|mancuernas|espalda,triceps|pull over',
    'cruce-poleas|Cruce de poleas|polea|hombros',
    'pec-deck|Aperturas en máquina|maquina||pec deck',
    'press-pecho-maquina|Press de pecho en máquina|maquina|triceps,hombros',
    'flexiones|Flexiones|corporal|triceps,hombros,core|push ups',
    'fondos-pecho|Fondos en paralelas para pecho|corporal|triceps,hombros',
    'press-banca-smith|Press banca en multipower|smith|triceps,hombros',
    'press-pecho-bandas|Press de pecho con bandas|bandas|triceps,hombros',
    'press-inclinado-maquina|Press inclinado en máquina|maquina|triceps,hombros|incline chest press',
    'press-inclinado-smith|Press inclinado en multipower|smith|triceps,hombros',
    'aperturas-inclinadas|Aperturas inclinadas con mancuernas|mancuernas|hombros|incline fly',
    'cruce-poleas-bajo|Cruce de poleas de abajo arriba|polea|hombros|low cable fly',
    'flexiones-declinadas|Flexiones declinadas|corporal|triceps,hombros,core|decline push ups',
    'press-declinado-mancuernas|Press declinado con mancuernas|mancuernas|triceps,hombros',
    'aperturas-polea-banco|Aperturas en polea en banco|polea|hombros|lying cable fly',
    'press-squeeze|Press con mancuernas juntas|mancuernas|triceps,hombros|squeeze press',
  ]),
  ...grupo('espalda', [
    'dominadas|Dominadas|corporal|biceps,antebrazo|pull ups',
    'dominadas-asistidas|Dominadas asistidas en máquina|maquina,corporal|biceps',
    'jalon-pecho|Jalón al pecho|polea|biceps|lat pulldown',
    'jalon-neutro|Jalón con agarre neutro|polea|biceps',
    'remo-barra|Remo con barra|barra|biceps,core|bent over row',
    'remo-mancuerna|Remo con mancuerna|mancuernas|biceps|remo unilateral',
    'remo-polea|Remo sentado en polea|polea|biceps',
    'remo-maquina|Remo en máquina|maquina|biceps',
    'remo-pecho-apoyado|Remo con pecho apoyado|mancuernas|biceps',
    'remo-t|Remo en T|barra|biceps|t bar row',
    'pullover-polea|Pullover en polea|polea|triceps',
    'remo-trx|Remo en TRX|trx|biceps,core',
    'remo-invertido|Remo invertido|corporal|biceps,core',
    'remo-bandas|Remo con bandas|bandas|biceps',
    'extension-lumbar|Extensiones lumbares|corporal|gluteos,isquiotibiales|hiperextensiones',
    'encogimientos|Encogimientos con mancuernas|mancuernas|antebrazo|shrugs',
    'dominadas-supinas|Dominadas supinas|corporal|biceps,antebrazo|chin ups',
    'jalon-supino|Jalón con agarre supino|polea|biceps|reverse grip pulldown',
    'jalon-unilateral|Jalón unilateral en polea|polea|biceps|single arm pulldown',
    'remo-polea-unilateral|Remo unilateral en polea|polea|biceps,core|single arm cable row',
    'remo-pendlay|Remo Pendlay|barra|biceps,core|pendlay row',
    'encogimientos-barra|Encogimientos con barra|barra|antebrazo|barbell shrug',
    'remo-seal|Remo Seal|barra|biceps|seal row',
    'remo-meadows|Remo Meadows|barra|biceps,antebrazo|meadows row',
    'rack-pull|Rack pull|barra|gluteos,isquiotibiales,antebrazo|peso muerto parcial',
    'jalon-maquina|Jalón en máquina|maquina|biceps|machine pulldown',
  ]),
  ...grupo('hombros', [
    'press-militar|Press militar|barra|triceps,core|overhead press',
    'press-hombro-mancuernas|Press de hombros con mancuernas|mancuernas|triceps',
    'press-arnold|Press Arnold|mancuernas|triceps',
    'press-hombro-maquina|Press de hombros en máquina|maquina|triceps',
    'elevacion-lateral|Elevaciones laterales|mancuernas||lateral raise',
    'elevacion-lateral-polea|Elevaciones laterales en polea|polea',
    'elevacion-frontal|Elevaciones frontales|mancuernas',
    'pajaros|Pájaros con mancuernas|mancuernas|espalda|reverse fly',
    'reverse-pec-deck|Aperturas inversas en máquina|maquina|espalda',
    'face-pull|Face pull|polea|espalda',
    'press-landmine|Press landmine|barra|triceps,core',
    'separacion-bandas|Separaciones con banda|bandas|espalda|band pull apart',
    'press-hombro-smith|Press de hombros en multipower|smith|triceps',
    'elevacion-lateral-maquina|Elevaciones laterales en máquina|maquina',
    'remo-menton|Remo al mentón|barra|espalda,biceps|upright row',
    'pajaros-polea|Pájaros en polea|polea|espalda|reverse cable fly',
    'elevacion-frontal-polea|Elevaciones frontales en polea|polea',
    'press-militar-sentado|Press militar sentado|barra|triceps|seated overhead press',
    'elevacion-y|Elevaciones en Y|mancuernas|espalda|y raise',
    'press-kettlebell|Press de hombro con kettlebell|kettlebell|triceps,core|kettlebell press',
    'elevacion-lateral-bandas|Elevaciones laterales con banda|bandas',
  ]),
  ...grupo('biceps', [
    'curl-barra|Curl con barra|barra|antebrazo',
    'curl-mancuernas|Curl con mancuernas|mancuernas|antebrazo',
    'curl-martillo|Curl martillo|mancuernas|antebrazo',
    'curl-inclinado|Curl inclinado con mancuernas|mancuernas',
    'curl-predicador|Curl predicador con barra|barra',
    'curl-polea|Curl en polea|polea',
    'curl-concentrado|Curl concentrado|mancuernas',
    'curl-maquina|Curl en máquina|maquina',
    'curl-bayesiano|Curl bayesiano en polea|polea||bayesian curl',
    'curl-arana|Curl araña|mancuernas||spider curl',
    'curl-martillo-cuerda|Curl martillo en polea con cuerda|polea|antebrazo|rope hammer curl',
    'curl-barra-z|Curl con barra Z|barra|antebrazo|ez bar curl',
    'curl-predicador-mancuerna|Curl predicador con mancuerna|mancuernas',
    'curl-zottman|Curl Zottman|mancuernas|antebrazo|zottman curl',
    'curl-polea-alta|Curl en polea alta|polea||high cable curl',
    'curl-trx|Curl de bíceps en TRX|trx|core',
  ]),
  ...grupo('triceps', [
    'extension-triceps-cuerda|Extensión de tríceps con cuerda|polea',
    'extension-triceps-barra|Extensión de tríceps en polea con barra|polea',
    'extension-triceps-cabeza|Extensión de tríceps sobre la cabeza|mancuernas',
    'extension-triceps-polea-cabeza|Extensión de tríceps sobre la cabeza en polea|polea',
    'press-frances|Press francés|barra|hombros|skull crusher',
    'press-cerrado|Press banca con agarre cerrado|barra|pecho,hombros',
    'patada-triceps|Patada de tríceps|mancuernas',
    'fondos-triceps|Fondos en paralelas para tríceps|corporal|pecho,hombros',
    'extension-triceps-unilateral|Extensión de tríceps unilateral en polea|polea',
    'press-frances-mancuernas|Press francés con mancuernas|mancuernas',
    'fondos-maquina|Fondos en máquina|maquina|pecho,hombros|dip machine',
    'fondos-banco|Fondos en banco|corporal|pecho,hombros|bench dips',
    'flexiones-diamante|Flexiones diamante|corporal|pecho,hombros|diamond push ups',
    'patada-triceps-polea|Patada de tríceps en polea|polea||cable kickback',
    'extension-triceps-maquina|Extensión de tríceps en máquina|maquina',
    'extension-triceps-bandas|Extensión de tríceps con banda|bandas',
  ]),
  ...grupo('antebrazo', [
    'curl-muneca|Curl de muñeca|mancuernas',
    'extension-muneca|Extensión de muñeca|mancuernas',
    'curl-inverso|Curl inverso con barra|barra|biceps',
    'colgar-barra|Colgarse de la barra|corporal|espalda',
    'agarre-disco|Agarre de disco en pinza|otros',
    'rodillo-muneca|Rodillo de muñeca|otros|hombros|wrist roller',
    'curl-muneca-espalda|Curl de muñeca por detrás con barra|barra||behind the back wrist curl',
  ]),
  ...grupo('cuadriceps', [
    'sentadilla|Sentadilla|barra|gluteos,core|back squat,sentadilla trasera',
    'sentadilla-frontal|Sentadilla frontal|barra|gluteos,core|front squat',
    'sentadilla-goblet|Sentadilla goblet|kettlebell|gluteos,core',
    'prensa-piernas|Prensa de piernas|maquina|gluteos',
    'hack-squat|Sentadilla hack|maquina|gluteos',
    'sentadilla-smith|Sentadilla en multipower|smith|gluteos,core',
    'extension-cuadriceps|Extensión de cuádriceps|maquina',
    'zancadas|Zancadas con mancuernas|mancuernas|gluteos,isquiotibiales',
    'sentadilla-bulgara|Sentadilla búlgara|mancuernas|gluteos,core',
    'step-up|Subida al cajón con mancuernas|mancuernas|gluteos|step up',
    'sentadilla-corporal|Sentadilla con peso corporal|corporal|gluteos',
    'sentadilla-trx|Sentadilla en TRX|trx|gluteos',
    'sentadilla-pendulo|Sentadilla péndulo|maquina|gluteos|pendulum squat',
    'prensa-horizontal|Prensa horizontal|maquina|gluteos|seated leg press',
    'zancadas-barra|Zancadas con barra|barra|gluteos,isquiotibiales,core',
    'sissy-squat|Sentadilla sissy|corporal|core|sissy squat',
    'belt-squat|Sentadilla con cinturón|maquina|gluteos|belt squat',
    'zancadas-caminando|Zancadas caminando|mancuernas|gluteos,isquiotibiales|walking lunges',
    'sentadilla-pistol|Sentadilla a una pierna|corporal|gluteos,core|pistol squat',
    'sentadilla-pared|Sentadilla isométrica en pared|corporal|gluteos|wall sit',
  ]),
  ...grupo('isquiotibiales', [
    'peso-muerto-rumano|Peso muerto rumano|barra|gluteos,espalda|rdl',
    'rumano-mancuernas|Peso muerto rumano con mancuernas|mancuernas|gluteos,espalda',
    'curl-femoral-tumbado|Curl femoral tumbado|maquina|gemelos',
    'curl-femoral-sentado|Curl femoral sentado|maquina|gemelos',
    'curl-nordico|Curl nórdico|corporal|gluteos',
    'buenos-dias|Buenos días|barra|gluteos,espalda|good morning',
    'rumano-unilateral|Peso muerto rumano a una pierna|mancuernas|gluteos,core',
    'curl-femoral-trx|Curl femoral en TRX|trx|gluteos,core',
    'curl-femoral-pie|Curl femoral de pie en máquina|maquina|gemelos|standing leg curl',
    'rumano-smith|Peso muerto rumano en multipower|smith|gluteos,espalda',
    'glute-ham-raise|Glute ham raise|maquina|gluteos,gemelos|ghr',
    'curl-femoral-fitball|Curl femoral con fitball|otros|gluteos,core',
    'peso-muerto-rigidas|Peso muerto con piernas rígidas|barra|gluteos,espalda|stiff leg deadlift',
  ]),
  ...grupo('gluteos', [
    'hip-thrust|Hip thrust con barra|barra|isquiotibiales,core',
    'hip-thrust-maquina|Hip thrust en máquina|maquina|isquiotibiales',
    'puente-gluteos|Puente de glúteos|corporal|isquiotibiales',
    'patada-gluteo|Patada de glúteo en polea|polea|isquiotibiales',
    'abduccion-maquina|Abducción de cadera en máquina|maquina',
    'abduccion-bandas|Abducción de cadera con banda|bandas',
    'pull-through|Pull through en polea|polea|isquiotibiales',
    'zancada-inversa|Zancada inversa con mancuernas|mancuernas|cuadriceps,core',
    'hip-thrust-smith|Hip thrust en multipower|smith|isquiotibiales,core',
    'patada-gluteo-maquina|Patada de glúteo en máquina|maquina|isquiotibiales|glute kickback',
    'abduccion-polea|Abducción de cadera en polea|polea',
    'sentadilla-sumo|Sentadilla sumo con mancuerna|mancuernas|aductores,cuadriceps,isquiotibiales|sumo squat',
    'puente-unilateral|Puente de glúteos a una pierna|corporal|isquiotibiales,core|single leg glute bridge',
    'hiperextension-gluteo|Hiperextensión para glúteo|corporal|isquiotibiales,espalda',
    'almejas|Almejas con banda|bandas||clamshell',
    'patada-cuadrupedia|Patada de glúteo en cuadrupedia|corporal|isquiotibiales|donkey kick',
  ]),
  ...grupo('aductores', [
    'aduccion-maquina|Aducción de cadera en máquina|maquina||hip adduction',
    'aduccion-polea|Aducción de cadera en polea|polea|core',
    'aduccion-bandas|Aducción de cadera con banda|bandas',
    'aduccion-tumbado|Aducción tumbado de lado|corporal|core|side lying adduction',
    'plancha-copenhague|Plancha Copenhague|corporal|core|copenhagen plank',
    'sentadilla-cosaca|Sentadilla cosaca|corporal|cuadriceps,gluteos|cossack squat',
    'zancada-lateral|Zancada lateral con mancuernas|mancuernas|cuadriceps,gluteos|side lunge',
    'aduccion-balon|Aducción isométrica con balón|otros||adductor squeeze',
  ]),
  ...grupo('gemelos', [
    'gemelos-maquina|Elevación de gemelos de pie en máquina|maquina',
    'gemelos-sentado|Elevación de gemelos sentado|maquina',
    'gemelos-prensa|Elevación de gemelos en prensa|maquina',
    'gemelos-unilateral|Elevación de gemelos a una pierna|corporal',
    'gemelos-smith|Elevación de gemelos en multipower|smith',
    'gemelos-mancuernas|Elevación de gemelos con mancuernas|mancuernas',
    'gemelos-burro|Elevación de gemelos tipo burro|maquina||donkey calf raise',
  ]),
  ...grupo('core', [
    'plancha|Plancha|corporal|hombros,gluteos',
    'plancha-lateral|Plancha lateral|corporal|hombros,gluteos',
    'crunch|Crunch abdominal|corporal',
    'crunch-polea|Crunch en polea|polea',
    'elevacion-piernas|Elevaciones de piernas colgado|corporal|antebrazo',
    'dead-bug|Dead bug|corporal',
    'bird-dog|Bird dog|corporal|espalda,gluteos',
    'pallof-press|Pallof press|polea',
    'rueda-abdominal|Rueda abdominal|otros|hombros,espalda|ab wheel',
    'woodchop|Woodchop en polea|polea|hombros',
    'crunch-inverso|Crunch inverso|corporal',
    'encogimiento-trx|Encogimientos de rodillas en TRX|trx|hombros',
    'crunch-maquina|Crunch en máquina|maquina',
    'elevacion-rodillas-paralelas|Elevaciones de rodillas en silla romana|corporal||captain chair,elevaciones de rodillas en paralelas',
    'giros-rusos|Giros rusos|corporal||russian twist',
    'inclinacion-lateral|Inclinaciones laterales con mancuerna|mancuernas||side bend',
    'elevacion-piernas-tumbado|Elevaciones de piernas tumbado|corporal||lying leg raise',
    'hollow-hold|Hollow hold|corporal||posicion hueca',
    'escaladores|Escaladores|corporal|hombros,cuadriceps|mountain climbers',
    'navaja|Abdominales en V|corporal||v ups,navaja',
    'crunch-bicicleta|Crunch bicicleta|corporal||bicycle crunch',
    'crunch-declinado|Crunch en banco declinado|corporal||decline crunch',
  ]),
  ...grupo('completo', [
    'peso-muerto|Peso muerto convencional|barra|gluteos,isquiotibiales,espalda,antebrazo',
    'peso-muerto-sumo|Peso muerto sumo|barra|gluteos,cuadriceps,isquiotibiales,espalda',
    'swing-kettlebell|Swing con kettlebell|kettlebell|gluteos,isquiotibiales,core',
    'thruster|Thruster con mancuernas|mancuernas|cuadriceps,hombros,core',
    'burpee|Burpees|corporal|pecho,cuadriceps,core',
    'farmer-walk|Paseo del granjero|mancuernas|antebrazo,core|farmer carry',
    'cargada-barra|Cargada con barra|barra|cuadriceps,gluteos,espalda|power clean',
    'turkish-get-up|Levantamiento turco|kettlebell|core,hombros,gluteos|turkish get up',
    'peso-muerto-trap-bar|Peso muerto con barra hexagonal|barra|cuadriceps,gluteos,isquiotibiales,espalda|trap bar deadlift',
    'empuje-trineo|Empuje de trineo|otros|cuadriceps,gluteos,gemelos|sled push',
  ]).map(e => ({ ...e, ...PARTICIPACION_COMPLETA[e.id], filterGroups: ['completo'] as Musculo[] })),
]
export const CATALOGO_POR_ID = new Map(CATALOGO_EJERCICIOS.map(e => [e.id, e]))
